CREATE TABLE matriculas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  nascimento DATE NOT NULL,
  naturalidade VARCHAR(100) NOT NULL,
  nacionalidade VARCHAR(100) NOT NULL,
  encarregado VARCHAR(100) NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  email VARCHAR(100) NOT NULL,
  curso VARCHAR(100) NOT NULL,
  classe VARCHAR(20) NOT NULL,
  ensino VARCHAR(20) NOT NULL,
  foto VARCHAR(255) NOT NULL,
  identificacao VARCHAR(255) NOT NULL,
  comprovativo VARCHAR(255) NOT NULL,
  data_inscricao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
